# Neo4j Helm Chart Values - Dev Environment
# See https://neo4j.com/docs/operations-manual/current/kubernetes/helm-charts-setup/
#
# Requires Neo4j 2025.10+ for native Vector type support.
# See: https://neo4j.com/blog/developer/introducing-neo4j-native-vector-data-type/

neo4j:
  # Use Enterprise Edition for backup support and Vector type
  edition: enterprise
  acceptLicenseAgreement: "yes"
  # Password is set via Terraform set_sensitive block
  # Resource Configuration (container limits/requests)
  resources:
    cpu: "1000m"
    memory: "10Gi"

# Plugin installation (copies APOC Core from /var/lib/neo4j/labs into /var/lib/neo4j/plugins)
env:
  NEO4J_PLUGINS: '["apoc"]'

# Service Configuration
services:
  # Enable external LoadBalancer for Bolt/HTTP access (dev)
  neo4j:
    enabled: true
    spec:
      type: LoadBalancer
  # Enable ClusterIP for in-cluster access
  default:
    enabled: true
    type: ClusterIP
  # Enable admin service for backups
  admin:
    enabled: true
    type: ClusterIP

# =============================================================================
# SECURITY NOTE: Development Configuration Only
# =============================================================================
# The following TLS settings are intentionally permissive for development:
# - HTTP enabled for Neo4j Browser access without certificates
# - HTTPS disabled to avoid certificate management overhead
# - Bolt TLS disabled (unencrypted connections)
#
# For production deployments, update these settings:
#   server.http.enabled: "false"           # Disable unencrypted HTTP
#   server.https.enabled: "true"           # Enable HTTPS
#   server.bolt.tls_level: "REQUIRED"      # Enforce TLS on Bolt connections
#   ssl.policy.bolt.enabled: "true"        # Enable Bolt SSL policy
#   ssl.policy.bolt.base_directory: "..."  # Path to certificates
#
# Production also requires:
# - TLS certificate provisioning (cert-manager or manual Kubernetes Secret)
# - Certificate secret mounted into the Neo4j pod
# =============================================================================

# Neo4j Configuration
config:
  # Cypher 25 is required for native Vector type support
  db.query.default_language: "CYPHER_25"

  # HTTP (Neo4j Browser) controlled by Terraform variable enable_neo4j_browser
  server.https.enabled: "false"

  # Bolt TLS disabled for dev - "OPTIONAL" requires SSL policy/certs to be configured.
  # For production with TLS, set to "REQUIRED" and configure ssl.policy.bolt.*
  server.bolt.tls_level: "DISABLED"

  # Enable backup listener
  server.backup.listen_address: "0.0.0.0:6362"
  server.backup.enabled: "true"

  # ==========================================================================
  # Memory Configuration (aligned with local Neo4j Desktop)
  # ==========================================================================
  # Heap: 4-5 GiB for transaction state and query context
  server.memory.heap.initial_size: "4G"
  server.memory.heap.max_size: "5G"

  # Page cache: 4 GiB for mapping store files
  server.memory.pagecache.size: "4G"

  # Transaction memory limits
  # Total max across all transactions
  dbms.memory.transaction.total.max: "4G"
  # Per-transaction max: 0B = unlimited (default, allows large single transactions)

  # ==========================================================================
  # APOC Core Plugin Configuration
  # ==========================================================================
  # APOC Core is installed into /var/lib/neo4j/plugins via NEO4J_PLUGINS.
  # See: https://neo4j.com/docs/operations-manual/current/kubernetes/plugins/
  server.directories.plugins: "/var/lib/neo4j/plugins"
  server.config.strict_validation.enabled: "false"

  # Security settings for APOC procedures
  dbms.security.procedures.unrestricted: "apoc.*"
  # Allow APOC; keep wildcard unless you want to restrict other procedures
  dbms.security.procedures.allowlist: "*"

# Optional: APOC-specific settings
apoc_config:
  apoc.trigger.enabled: "true"
  apoc.import.file.enabled: "true"

# Volume Configuration
# NOTE: Storage size is overridden by Terraform variable neo4j_storage_size
volumes:
  data:
    mode: "defaultStorageClass"
    defaultStorageClass:
      requests:
        storage: 25Gi

# Resource Configuration for Autopilot (legacy key)
# NOTE: The chart uses `neo4j.resources` for the main container. Keep this in
# sync or remove after confirming no other chart components depend on it.
resources:
  requests:
    cpu: "500m"
    memory: "10Gi"

# Pod Configuration
podSpec:
  # Allow scheduling on any node (Autopilot handles this)
  nodeSelector: {}
  tolerations: []
  # Explicitly include pods in the LoadBalancer selector
  loadbalancer: include
  # Pod-level security context
  # See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  securityContext:
    runAsNonRoot: true
    runAsUser: 7474       # Standard Neo4j UID in official images
    runAsGroup: 7474
    fsGroup: 7474         # Required for volume access
    seccompProfile:
      type: RuntimeDefault

# Container Security Context
# Note: readOnlyRootFilesystem must be false - Neo4j requires write access to
# /var/lib/neo4j/data, /var/lib/neo4j/logs, and /tmp for normal operation.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Logging
logs:
  # Send logs to stdout for collection
  redirectQueryLog: true

# Metrics (optional - enable if using Prometheus)
metrics:
  prometheus:
    enabled: false
